### ISSUE TITLE
react example cannot be run successfully.

### ISSUE THREAD

**Issue by johnzheng1975** [theintern/intern-examples#34]
$ cd react-example 

$ npm test

> react-intern-example@0.1.0 test C:\Users\HP Sprout\intern-examples\react-example
> intern-runner config=tests/intern

Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
FATAL ERROR
ReferenceError: __cov_9fswQrlBf7FYU_5dADJK0A is not defined
  at <node_modules\intern\lib\interfaces\object.js:9:1>
  at exports.runInThisContext  vm.js:54:17
  at Object.vm.runInThisContext  <node_modules\istanbul\lib\hook.js:163:16>
  at <node_modules\dojo\dojo.js:760:8>
  at FSReqWrap.readFileAfterClose [as oncomplete]  fs.js:380:3
npm ERR! Test failed.  See above for more details.

**Comment by johnzheng1975** [comment]
Note that seems I install successfully:
$ npm install
npm WARN prefer global istanbul@0.2.16 should be installed with -g

> react-intern-example@0.1.0 postinstall C:\Users\HP Sprout\intern-examples\react-example
> bower install

bower director#^1.2.0           cached git://github.com/flatiron/director.git#1.2.8
bower director#^1.2.0         validate 1.2.8 against git://github.com/flatiron/director.git#^1.2.0
bower todomvc-app-css#^1.0.0    cached git://github.com/tastejs/todomvc-app-css.git#1.0.3
bower todomvc-app-css#^1.0.0  validate 1.0.3 against git://github.com/tastejs/todomvc-app-css.git#^1.0.0
bower react#^0.12.0             cached git://github.com/facebook/react-bower.git#0.12.2
bower react#^0.12.0           validate 0.12.2 against git://github.com/facebook/react-bower.git#^0.12.0
bower todomvc-common#^1.0.1     cached git://github.com/tastejs/todomvc-common.git#1.0.2
bower todomvc-common#^1.0.1   validate 1.0.2 against git://github.com/tastejs/todomvc-common.git#^1.0.1
bower intern#~2.2.2             cached git://github.com/theintern/intern.git#2.2.2
bower intern#~2.2.2           validate 2.2.2 against git://github.com/theintern/intern.git#~2.2.2
bower todomvc-common#^1.0.1    install todomvc-common#1.0.2
bower react#^0.12.0            install react#0.12.2
bower director#^1.2.0          install director#1.2.8
bower intern#~2.2.2            install intern#2.2.2
bower todomvc-app-css#^1.0.0   install todomvc-app-css#1.0.3

todomvc-common#1.0.2 bower_components\todomvc-common

react#0.12.2 bower_components\react

director#1.2.8 bower_components\director

intern#2.2.2 bower_components\intern

todomvc-app-css#1.0.3 bower_components\todomvc-app-css

$

**Comment by johnzheng1975** [comment]
Unit testing still raise exception after I comment functional testing in intern.js
functionalSuites: [  /*'tests/functional/Todo' */ ]


$ npm test

> react-intern-example@0.1.0 test C:\Users\HP Sprout\intern-examples\react-example
> intern-runner config=tests/intern

Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
Transformation error; return original code
[TypeError: SourceNode is not a function]
FATAL ERROR
undefined: __cov_f4i9xCHhhsOG1ythn$39BA is not defined
ReferenceError: __cov_f4i9xCHhhsOG1ythn$39BA is not defined
  at <js\utils.js:9:1>
FAIL: main - todoModel - default data (1ms)
TypeError: Cannot read property 'store' of undefined
  at new app.TodoModel  <C:\Users\HP Sprout\intern-examples\react-example\js\todoModel.js:23:2>
  at Test.registerSuite.default data [as test]  <tests\todoModel.js:15:21>
  at Test.run  <__intern\lib\Test.js:169:19>
  at <__intern\lib\Suite.js:237:13>
  at signalListener  <__intern\node_modules\dojo\Deferred.js:37:21>
  at Promise.then.promise.then  <__intern\node_modules\dojo\Deferred.js:258:5>
  at runTest  <__intern\lib\Suite.js:236:46>
  at <__intern\lib\Suite.js:249:7>
FAIL: main - todoModel - complete (empty model) (0ms)
TypeError: Cannot read property 'store' of undefined
  at new app.TodoModel  <C:\Users\HP Sprout\intern-examples\react-example\js\todoModel.js:23:2>
  at Test.registerSuite.complete  <empty model>
  at Test.run  <__intern\lib\Test.js:169:19>
  at <__intern\lib\Suite.js:237:13>
  at signalListener  <__intern\node_modules\dojo\Deferred.js:37:21>
  at Promise.then.promise.then  <__intern\node_modules\dojo\Deferred.js:258:5>
  at runTest  <__intern\lib\Suite.js:236:46>
  at <__intern\lib\Suite.js:249:7>

------------------------------------------------------------------|-----------|-----------|-----------|-----------|
File                                                              |   % Stmts |% Branches |   % Funcs |   % Lines |
------------------------------------------------------------------|-----------|-----------|-----------|-----------|
   js\                                                            |     38.89 |     33.33 |      12.5 |        40 |
      todoModel.js                                                |     38.89 |     33.33 |      12.5 |        40 |
   node_modules\escodegen\node_modules\source-map\lib\source-map\ |      1.24 |         0 |         0 |      1.25 |
      source-node.js                                              |      1.24 |         0 |         0 |      1.25 |
------------------------------------------------------------------|-----------|-----------|-----------|-----------|
All files                                                         |      8.12 |      2.35 |      5.56 |      8.21 |
------------------------------------------------------------------|-----------|-----------|-----------|-----------|

2/2 tests failed
PASS: main - footer - construction (2ms)
0/0 tests failed
PASS: main - todoModel - default data (0ms)
PASS: main - todoModel - complete (empty model) (1ms)
0/2 tests failed
PASS: main - footer - construction (0ms)
PASS: main - footer - render (1ms)
0/2 tests failed
0/4 tests failed

-------------------|-----------|-----------|-----------|-----------|
File               |   % Stmts |% Branches |   % Funcs |   % Lines |
-------------------|-----------|-----------|-----------|-----------|
   js\             |     74.58 |     66.67 |     47.62 |     75.86 |
      todoModel.js |     61.11 |     16.67 |      37.5 |     62.86 |
      utils.js     |     95.65 |     80.95 |        80 |     95.65 |
-------------------|-----------|-----------|-----------|-----------|
All files          |     74.58 |     66.67 |     47.62 |     75.86 |
-------------------|-----------|-----------|-----------|-----------|

0/4 tests failed
npm ERR! Test failed.  See above for more details.
