### ISSUE TITLE
Backbone example doesn't work

### ISSUE THREAD

**Issue by palewire** [theintern/intern-examples#36]
I just cloned the repo and followed the directions. Here's the error I got:

```
 % npm test

> backbone-intern-example@0.1.0 test /home/ben/Code/intern-examples/backbone-example
> intern-runner config=tests/intern

/home/ben/Code/intern-examples/backbone-example/node_modules/dojo/dojo.js:757
                                        throw new Error('Failed to load module ' + module.mid + ' from ' + url + (parent ? ' (parent: ' + parent.mid + ')' : ''));
                                        ^

Error: Failed to load module intern/node_modules/dojo/node from /home/ben/Code/intern-examples/backbone-example/node_modules/intern/node_modules/dojo/node.js (parent: intern/node_modules/dojo/node!2!*)
    at ReadFileContext.callback (/home/ben/Code/intern-examples/backbone-example/node_modules/dojo/dojo.js:757:12)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
npm ERR! Test failed.  See above for more details.
```

**Comment by rozaev** [comment]
@palewire This is fixed.
